name: 'agrotest'
version: '1.0.0'
profile: 'agrotest'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  agrotest:
    stg:
      +materialized: table
    ods:
      +materialized: table
    dds:
      +materialized: table
    cdm:
      +materialized: view
    dm:
      +materialized: view

seeds:
  agrotest:
    +schema: stg
